export const actionTypes = {
  POKEMONS_FETCH_ALL_PENDING: "POKEMONS_FETCH_ALL_PENDING",
  POKEMONS_FETCH_ALL_SUCCESS: "POKEMONS_FETCH_ALL_SUCCESS",
  POKEMONS_FETCH_ALL_FAILURE: "POKEMONS_FETCH_ALL_FAILURE",
  
  POKEMONS_FETCH_MORE_PENDING: "POKEMONS_FETCH_MORE_PENDING",
  POKEMONS_FETCH_MORE_SUCCESS: "POKEMONS_FETCH_MORE_SUCCESS",
  POKEMONS_FETCH_MORE_FAILURE: "POKEMONS_FETCH_MORE_FAILURE",
}